EATI_django/urls.py
from django.contrib import admin
from django.urls import path
from imageboard import urls as board_urls
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(board_urls, namespace='board_feed')),
    path('', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

imageboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'imageboard'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'), 
    path('post/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('createpost/', AddPostView.as_view(), name='create_post'),
]

imageboard/models.py
from django.db import models
from sorl.thumbnail import ImageField
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class Post(models.Model):
    title = models.CharField(max_length=120)
    text = models.CharField(max_length=1024)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    img = ImageField()
    
    def __str__(self):
        return self.title[0:100]
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField(max_length=600)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.text

imageboard/forms.py
from django import forms
from .models import Comment, Post
from django.utils import timezone

class PostForm(forms.ModelForm):
    title = forms.CharField(label='Titulo')
    text = forms.CharField(label='Texto')
    img = forms.ImageField(label='Imagen')
    
    class Meta:
        model = Post
        fields = ['title', 'text', 'img']

class CommentForm(forms.ModelForm):
    text = forms.CharField(label='Tu comentario')
    
    class Meta:
        model = Comment
        fields = ['text']
        

EATI_django/views.py
from django.shortcuts import render, redirect

imageboard/views.py
from django.shortcuts import redirect, get_object_or_404
from .models import Post, Comment
from .forms import CommentForm, PostForm
from django.views.generic import TemplateView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse




class HomePageView(TemplateView):
    template_name = 'imageboard/index.html'
    
    #Obtengo el contexto extrayendo todos los posts del modelo Post para mostrarlos en la plantilla.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id') 
        return context
    
class PostDetailView(LoginRequiredMixin, DetailView):
    template_name = 'imageboard/detail.html'
    model = Post
    context_object_name = 'post'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        comments = Comment.objects.filter(post=post).order_by('-id') 
        context['comments'] = comments
        context['comment_form'] = CommentForm() 
        return context
    
    def post(self, request, *args, **kwargs):
        post = self.get_object()
        form = CommentForm(request.POST)
        
        if 'delete_comment_id' in request.POST:
            comment_id = request.POST['delete_comment_id']
            comment = get_object_or_404(Comment, pk=comment_id)
            comment.delete()
            # Redirect to the same post detail page after deleting the comment
            return redirect(reverse('imageboard:detail', kwargs={'pk': post.pk}))
        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect(reverse('imageboard:detail', kwargs={'pk': post.pk}))
        else:
            # If form is invalid, re-render the page with errors
            context = self.get_context_data()
            context['comment_form'] = form
            return self.render_to_response(context)
            
class AddPostView(LoginRequiredMixin, CreateView):
    template_name = 'imageboard/post.html'
    model = Post
    form_class = PostForm
    
    def form_valid(self, form):
        form.instance.author = self.request.user 
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('imageboard:detail', kwargs={'pk': self.object.pk})
    
    

imageboard/templates/imageboard/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'imageboard/styles.css' %}" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include "imageboard/navbar.html" %}
    {% block body %} {% endblock body %}
  </body>
</html>

imageboard/templates/imageboard/detail.html
{% extends "imageboard/base.html" %}
{% load thumbnail %}

{% block title %}{{ post.title }}{% endblock %}
{% block body %}
    <div class="content">
        <div class="content-post">
            <img class="post-image" src="{{ post.img.url }}" alt="{{ post.title }}">
            <h1>{{ post.title }}</h1>
            <p>{{ post.text }}</p>
            <p class="author">Posteado por {{ post.author }} | {{ post.date }}</p>
        </div>
        <div class="content-comments">
            {% if request.user.is_authenticated %}
                <form method="POST" action="" enctype="multipart/form-data" class="comment-form">
                    <h1>Posteá un comentario</h1>
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <div>
                        <button type="submit" class="button">Postear</button>
                    </div>
                </form>
            {% endif %}
            {% for comment in comments %}
                <div class="content-comment">
                    <div class="comment-info">
                        <p>{{ comment.author }}</p>
                        <div>
                            <p> {{ comment.date }} </p>
                            {% if request.user == comment.author %}
                                <form method="post" action="">
                                    {% csrf_token %}
                                    <input type="hidden" name="delete_comment_id" value="{{ comment.id }}">
                                    <button class="comment-del" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
                                      </svg></button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                        <div class="comment-text">
                            <p>{{ comment.text }}</p>
                        </div>
                </div>
            {% empty %}
                <h1>Todavía no hay comentarios</h1>
            {% endfor %}
        </div>
    </div>
{% endblock %}

imageboard/templates/imageboard/index.html
{% extends "imageboard/base.html" %} 
{% load thumbnail %} 

{% block title %}Dubix{% endblock %} 

{% block body %}


<div class="board">
    {% for post in posts %} 
        {% thumbnail post.img "200x200" crop="center" as im %}
            <a class="post-card" href="{% url 'imageboard:detail' post.id %}" style="background-image: url('{{im.url}}');">
                <div class="post-title">{{ post.title }}</div>
            </a>
        {% endthumbnail %}
    {% endfor %} 
</div>
{% endblock %}

imageboard/templates/imageboard/navbar.html
<nav class="navbar">
  <div class="nav-content">
      <a class="nav-logo" href="/">DUBIX</a>
      <ul class="nav-items">
      {% if request.user.is_authenticated %}
            <li><a href="{% url 'account_logout' %}">Salir de la cuenta</a></li>
            <li><a href="{% url 'imageboard:create_post' %}">Postear</a></li>
            <li>Bienvenido! {{ user.username }}</li>
          {% else %}
            <li><a href="{% url 'account_signup' %}">Registrarse</a></li>
            <li><a href="{% url 'account_login' %}">login</a></li>
          {% endif %}
        </ul>
  </div>
</nav>

imageboard/templates/imageboard/post.html
{% extends "imageboard/base.html" %}

{% block title %}
    Crear nuevo posteo
{% endblock %}

{% block body %}
    <div class="new-post">
        <h1>Crear nuevo posteo</h1>
        <form method="POST" enctype="multipart/form-data" class="new-post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="button" type="submit" value="Crear post">
        </form>
    </div>
{% endblock %}